import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillFacebook, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar.png";
import frontend from "../public/frontend.png";
import backend from "../public/backend.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amar Alibegovic Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen ">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons dark:text-gray-400">
              Amar Alibegovic
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-gray-400 dark:hover:text-yellow-300 hover:text-yellow-400"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to bg-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1fkh0O8oMyCdBOJLeWtGs6qM2-a0dzjxd/view?usp=sharing"
                  alt="Download Resume"
                  download
                  target='_blank'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Amar Alibegović
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-400">
              Web Developer
            </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-500">
              I'm a web developer with a focus on the MERN stack, but still
              exploring other technologies and frameworks that catch my
              interest! If you're looking for a developer to add to your team,
              I'd love to hear from you!
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 ">
            <a
              href="https://www.linkedin.com/in/amar-alibegovic-71728b138/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://www.facebook.com/spiculus/" target="_blank">
              <AiFillFacebook />
            </a>
            <a href="https://github.com/Spiculus89" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={avatar} layout="cover" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-400 mt-12 text-center">
              My skills
            </h3>
          </div>
          <div className=" lg:flex justify-center gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <Image
                className="mx-auto"
                src={frontend}
                width={100}
                alt="frontend"
                height={100}
              />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-gray-300">
                Frontend
              </h3>
              <h4 className=" py-4 text-teal-600">Technologies that I use</h4>
              <p className=" text-gray-800 py-1 dark:text-gray-400">ReactJs</p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">NextJs</p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">Redux</p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">
                MaterialUI
              </p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">
                SemanticUI
              </p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">
                Bootstrap
              </p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">Tailwind</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-700">
              <Image
                className="mx-auto"
                src={backend}
                width={100}
                height={100}
                alt="backend"
              />
              <h3 className=" text-lg font-medium pt-8 pb-2 dark:text-gray-300">
                Backend
              </h3>
              <h4 className=" py-4 text-teal-600">Technologies that I use</h4>
              <p className=" text-gray-800 py-1 dark:text-gray-400">NodeJs</p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">MongoDb</p>
              <p className=" text-gray-800 py-1 dark:text-gray-400">Express</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-400 mt-12 text-center">
              Portfolio
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-500">
              These are some of my projects I've done so far. You can live
              preview all of them, but if you want to check out the code, feel
              free to contact me.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Pizza Order Composer
              </p>
              <div className="web web1">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-5">
                      <h3 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h3>
                      <p>React</p>
                      <p>Bootstrap</p>
                      <p>Json Web token</p>
                      <p>Redux</p>
                      <p>Express Validator</p>
                      <p>Mongoose</p>
                      <p>Bcrypt JS</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://pizza-order-mpdr.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Youtube Comment Analyst
              </p>
              <div className="web web2">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>Axios</p>
                      <p>Semantic-UI</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://youtube-comment-analyst.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                IMDB Search
              </p>
              <div className="web web3">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>Axios</p>
                      <p>material-UI</p>
                      <p>Redux</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://imdb-search.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Rock Paper Scissors
              </p>
              <div className="web web4">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>Redux</p>
                      <p>Material-UI</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://rock-paper-scissors-uwdu.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Book Recommender
              </p>
              <div className="web web5">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>Axios</p>
                      <p>Semantic-UI</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://book-recommendation-w9v6.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Yatzy
              </p>
              <div className="web web6">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>CSS - no library</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://yatzy.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Weather App
              </p>
              <div className="web web7">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>Material-UI</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://weather-app-5sqs.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Tic Tac Toe
              </p>
              <div className="web web8">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>CSS - no library</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://tic-tac-toe-5su7.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Minesweeper
              </p>
              <div className="web web9">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>CSS - no library</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://minesweeper-ma2t.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
            <div className=" basis-1/3 flex-1 ">
              <p className=" text-2xl text-center mb-4 dark:text-gray-300">
                Hangman
              </p>
              <div className="web web10">
                <div className="info flex gap-5">
                  <ul className=" basis-1/3 flex-1 my-auto">
                    <div className="flex flex-col text-center m-10">
                      <h5 className="text-1l py-2 md:text-2l dark:text-gray-400">
                        Technologies used
                      </h5>
                      <p>React</p>
                      <p>CSS - no library</p>
                      <p>Axios</p>
                    </div>
                  </ul>
                  <a
                    className=" basis-1/3 my-auto"
                    href="https://hangman-54cu.onrender.com"
                    target="_blank"
                  >
                    Live preview
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
